language: node_js
before_install: npm install -g mocha
node_js:
- '0.10'
deploy:
  provider: s3
  access_key_id: AKIAJN7ZXY2IBJ63OOXA
  secret_access_key:
    secure: ZgxNARNeWRYVwb4mKInxdhO+LpYP5Pdqffz4+MCxmNc5Dqgb67phr6CLnfQocWiLk0rD3AfgJSCPiHrRYFoRQluqOqjznSqKp+TB0n0eUZ2sEQcaXzWVhsCHuvbdGItz1hAafsectI2UvGQCwGpS+1RjGln/31DvBb4TwE20Cyg=
  bucket: deploy-weeia
  upload-dir: wozniak
  acl: public_read
  on:
    repo: piotrek92/ciTest-Wozniak-
